Hw02 unpack string completed
ArcSigov/homeworks pull request #2
Opened 2023-06-12 09:41 UTC by ArcSigov

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-12 11:25 UTC, engineer-go requested changes
Добрый день, Аркадий. Большое спасибо, что выполняете вовремя ДЗ. Вижу что у вас получилось решить задание, но сейчас оно довольно сложно для понимания, и имеет объём кода больше рекомендуемого. Я бы рекомендовал вам попробовать упростить решение. Нам нет необходимости иметь 2 различных метода, достаточно просто по мере итерации по строке сохранять за пределами итерации предыдущий символ, и является ли он экранирующим. А дальше просто через тот же if/else мы проводим распаковку строки согласно заданию. Так мы сильно уменьшим объём кода, и упростим его понимание. Рекомендую попробовать решить таким образом, если будут вопросы, обращайтесь в чат.

2023-06-12 20:14 UTC, ityulkanov reviewed
Уже намного лучше. Отписал ещё пару комментов как можно попробовать сократить то что получилось. Также не забывайте, что условия для if можно использовать вместе через &&

2023-06-12 20:14 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +			} else if prev.character >= "0" && prev.character <= "9" {
добрый вечер. Вижу что линтер ругается на повышенную когнитивную сложность) В общем не могу не согласиться. Но тут уже ближе к тому что я обычно вижу, поэтому предлагаю попробовать сделать рефакторинг, и посмотреть что получится. К примеру вот этот метод проверки на то является ли руна цифрой можно довольно легко вынести в какой нибудь isDigit(r rune) bool и вызывать его.

2023-06-12 20:14 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +		if err == nil {
как и писал в чате, не рекомендую основывать логику на наличии (или отсутствии) ошибок. Т.е. тут дожно стоять только if err != nil но никак не то что дальше. В рабочем коде такое бы выглядело как минимум непривычно

2023-06-12 20:14 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +				prev.isSlashed = true
все операции назначения чем будет являться поля стракта лучше делать там, где мы заканчиваем исполнение кода (обычно это перед return вызовом, либо в окончании цикла).

2023-06-12 20:58 UTC, ArcSigov commented on hw02_unpack_string/unpack.go
> +		if err == nil {
Поправил

2023-06-12 21:04 UTC, ArcSigov commented on hw02_unpack_string/unpack.go
> +			} else if prev.character >= "0" && prev.character <= "9" {
Да, согласен - это добавляет читабельность, допишу

2023-06-13 14:42 UTC, ityulkanov reviewed
Так, финальная прямая, сейчас когда у нас уже код стал намного чище, есть 2 вопроса: зачем нам нужны 2 свича, можно ли обойтись одним, и зачем нам логика с atoi когда мы можем в одном из case прописать strconf.isDigit(rune), и если true то там же и добавлять нужное количество символов?

2023-06-13 14:46 UTC, engineer-go approved these changes

2023-06-13 15:24 UTC, merged