Hw05 parallel execution
ArcSigov/homeworks pull request #6
Opened 2023-07-19 10:19 UTC by ArcSigov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-24 11:01 UTC, ityulkanov requested changes
поправьте, пожалуйста ошибку в строке 18, и я что то не нахожу как мы тут используем отрицательное значение m (maxErrors) которое было в ДЗ. Также рекомендую проверять не только m но и n на валидные значения

2023-07-24 11:01 UTC, engineer-go commented on hw05_parallel_execution/run.go
> +	errors := int32(-1)
вот тут у вас похоже ошибка, т.к. количество ошибок не должно начинаться  с отрицательной цифры

2023-07-24 11:01 UTC, engineer-go commented on hw05_parallel_execution/run.go
> +					break
чтобы не перегружать код воркера, можно было бы перенести проверку в цикл где вы вычитываете таски

2023-07-24 11:01 UTC, engineer-go commented on hw05_parallel_execution/run.go
> +				} else if tFunc, ok := <-tch; ok {
а почему в tsh вы решили складывать rangeом, а здесь range решили не использовать?

2023-08-09 13:21 UTC, ArcSigov commented on hw05_parallel_execution/run.go
> +					break
поправил

2023-08-09 13:22 UTC, ArcSigov commented on hw05_parallel_execution/run.go
> +				} else if tFunc, ok := <-tch; ok {
Да, согласен, ранее опыта работы на го с каналами не имел)

2023-08-11 04:07 UTC, ityulkanov approved these changes

2023-08-11 04:07 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +				if result := tFunc(); result != nil {
```suggestion
				if err := tFunc(); err != nil {
```

2023-08-11 04:10 UTC, ityulkanov commented on hw05_parallel_execution/run_test.go
> +		errorr := Run(tasks, workersCount, maxErrorsCount)
```suggestion
		error := Run(tasks, workersCount, maxErrorsCount)
```

2023-08-11 04:18 UTC, merged